modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="forest_legacy"
version="1.4.0.1"
displayName="Forest X Legacy"
displayURL="https://power-umc.ru/minecraft-java-edition/mods/5-forest-x-reborn.html"
logoFile="logo.png"
credits="Created by MagicalAlexey with the support of 7ZLBeka, maxD, Samuelchik"
authors="Environment Studios"
description="Forest X is a popular mod for Minecraft Java Edition, which adds new biomes, trees, as well as various flowers, berry bushes, building blocks and much more to the game.."

[[dependencies.forest_legacy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.forest_legacy]]
    modId="geckolib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.forest_legacy]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.forest_legacy]]
    modId="allmods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

